#!/usr/bin/env python
"""
Test to reproduce the Python 2->3 pickle issue with float-containing expressions.

The issue occurs when a sympy expression containing a float is pickled in Python 2
and then unpickled in Python 3. The problem is that Python 2 adds an 'L' suffix
to long integers in the pickle format, which causes issues when unpickling in Python 3.
"""

import pickle
import sys
import sympy
from sympy.core.numbers import Float

def test_python2_to_python3_pickle_with_float():
    """
    Test that reproduces the issue where pickling a sympy expression with a float
    in Python 2 and unpickling in Python 3 fails with ValueError.

    We manually create the problematic pickle data that would be generated by Python 2.
    """
    # Create a Float object
    f = Float(1.0)

    # Get the internal mpf tuple representation
    mpf_tuple = f._mpf_

    # Create a modified version that simulates Python 2 pickle format
    # In Python 2, when pickling, integers might get an 'L' suffix
    # The tuple format is (sign, mantissa_hex, exponent, bitcount)
    # We'll create a tuple where the mantissa is a string with 'L' suffix
    sign, man, expt, bc = mpf_tuple

    # Convert mantissa to hex string and add 'L' suffix (simulating Python 2 pickle)
    man_hex = hex(man)[2:]  # Remove '0x' prefix
    if not man_hex.endswith('L'):
        man_hex += 'L'

    # Create the problematic tuple that would be unpickled
    problematic_tuple = (sign, man_hex, expt, bc)

    # Now try to create a Float from this tuple (simulating unpickling)
    # On the base commit, this should fail with:
    # ValueError: invalid literal for int() with base 16: '...L'
    try:
        result = Float(problematic_tuple)
        # If we get here, the unpickling succeeded
        print("Test passed - Float created successfully from Python 2-style tuple")
        return True
    except ValueError as e:
        if "invalid literal for int() with base 16" in str(e):
            print(f"Test failed with expected error (base commit behavior): {e}")
            return False
        else:
            # Unexpected error
            print(f"Test failed with unexpected error: {e}")
            raise
    except Exception as e:
        print(f"Test failed with unexpected exception: {e}")
        raise

if __name__ == "__main__":
    success = test_python2_to_python3_pickle_with_float()
    if not success:
        # Exit with non-zero code to indicate failure
        sys.exit(1)
    else:
        sys.exit(0)